# -*- coding: utf-8 -*-
# Copyright (C) 2026 Héctor J. Benítez Corredera <xebolax@gmail.com>
# Este archivo está cubierto por la Licencia Pública General de GNU.
# Consulte el archivo COPYING.txt para más detalles.

"""
Diccionarios de traducciones para emoticonos y emojis.

Contiene:
- Traducciones de descripciones de emoticonos (inglés → español).
- Traducciones manuales de emojis Unicode frecuentes.
- Diccionario de emoticonos clásicos ASCII.
"""

# Traducciones de descripciones de emoticonos de la librería emot (inglés → español)
TRADUCCIONES_EMOTICONOS = {
	"Happy face smiley": "cara feliz",
	"Happy face or smiley": "cara feliz",
	"Laughing": "risa",
	"Wink or smirk": "guiño o sonrisa pícara",
	"Sad face": "cara triste",
	"Cry": "llanto",
	"Tongue sticking out, cheeky, playful or blowing a raspberry": "sacando la lengua, juguetón o burlón",
	"Surprise": "sorpresa",
	"Confused": "confundido",
	"Sealed lips or kiss": "labios sellados o beso",
	"Angel, saint or innocent": "ángel o inocente",
	"Evil or devilish": "diabólico",
	"Cool": "genial",
	"Embarrassed": "avergonzado",
	"Shy": "tímido",
	"Skeptical, annoyed, undecided, uneasy or hesitant": "escéptico o indeciso",
	"Straight face": "cara seria",
	"Grin": "sonrisa amplia",
	"Very happy": "muy feliz",
	"Love": "amor",
	"Kiss": "beso",
	"Cat face": "cara de gato",
	"Robot": "robot",
	"Rose": "rosa",
	"Heart": "corazón",
	"Broken heart": "corazón roto",
	"Sleeping": "durmiendo",
	"Rolling on the floor laughing": "riendo a carcajadas",
	"Disapproval": "desaprobación",
	"Yum or happy": "feliz o saboreando",
	"Silence": "silencio",
	"Thinking": "pensando",
	"Shock": "impacto",
	"Unsure": "inseguro",
	"Party": "fiesta",
	"Music": "música",
	"Happy crying": "llorando de alegría",
	"Dead": "muerto o agotado",
	"Strong laughter": "risa fuerte",
	"Plain": "expresión neutra",
	"Sarcasm": "sarcasmo",
	"Angry": "enfadado",
	"Very sad": "muy triste",
	"Applause": "aplausos",
	"High five": "choca esos cinco",
	"Peace": "paz",
	"Ok": "de acuerdo",
	"Thumbs up": "pulgar arriba",
	"Thumbs down": "pulgar abajo",
	"Frown, sad, angry or pouting": "triste, enfadado o haciendo pucheros",
	"Very very Happy face or smiley": "cara muy muy feliz",
	"Happy face with a wink": "cara feliz con guiño",
	"Happy face with a wink or smirk": "cara feliz con guiño o pícara",
	"Tongue sticking out, cheeky/playful": "sacando la lengua, juguetón",
	"Horror": "horror",
	"Bored": "aburrido",
	"In love": "enamorado",
	"Crying": "llorando",
	"Screaming": "gritando",
	"Skeptical": "escéptico",
	"Nerd": "empollón",
	"Tongue-in-cheek": "con ironía",
	"Playful": "juguetón",
	"Wink": "guiño",
	"Happy or embarrassed": "feliz o avergonzado",
}

# Traducciones manuales para emojis Unicode
TRADUCCIONES_EMOJIS_MANUAL = {
	# === Caras sonrientes ===
	"😀": "cara sonriendo",
	"😃": "cara sonriendo con boca abierta",
	"😄": "cara sonriendo con ojos sonrientes",
	"😁": "cara radiante",
	"😆": "cara riendo con ojos cerrados",
	"😅": "cara sonriendo con sudor",
	"🤣": "riendo a carcajadas",
	"😂": "cara llorando de risa",
	"🙂": "cara sonriente",
	"🙃": "cara al revés",
	"🫠": "cara derritiéndose",
	"😉": "cara guiñando un ojo",
	"😊": "cara sonriente con rubor",
	"😇": "cara de ángel",
	"🥲": "cara sonriente con lágrima",

	# === Caras afectuosas ===
	"🥰": "cara con corazones",
	"😍": "cara enamorada",
	"🤩": "cara fascinada",
	"😘": "cara lanzando un beso",
	"😗": "cara de beso",
	"😚": "cara besando con ojos cerrados",
	"😙": "cara besando con ojos sonrientes",
	"🥳": "cara de fiesta",

	# === Caras con lengua ===
	"😋": "cara saboreando",
	"😛": "cara sacando la lengua",
	"😜": "cara guiñando y sacando la lengua",
	"🤪": "cara alocada",
	"😝": "cara con lengua y ojos cerrados",
	"🤑": "cara con dinero",

	# === Caras con manos ===
	"🤗": "cara abrazando",
	"🤭": "cara tapándose la boca",
	"🫢": "cara con boca abierta tapándose",
	"🫣": "cara mirando entre los dedos",
	"🤫": "cara pidiendo silencio",
	"🤔": "cara pensando",
	"🫡": "cara haciendo saludo militar",

	# === Caras neutras/escépticas ===
	"🤐": "cara con boca cerrada",
	"🤨": "cara con ceja levantada",
	"😐": "cara neutra",
	"😑": "cara inexpresiva",
	"😶": "cara sin boca",
	"🫥": "cara con línea punteada",
	"😶‍🌫️": "cara entre nubes",
	"😏": "cara pícara",
	"😒": "cara de desagrado",
	"🙄": "ojos en blanco",
	"😬": "cara de mueca",
	"😮‍💨": "cara suspirando",
	"🤥": "cara mentirosa",

	# === Caras soñolientas ===
	"😌": "cara aliviada",
	"😔": "cara pensativa",
	"😪": "cara somnolienta",
	"🤤": "cara babeando",
	"😴": "cara durmiendo",

	# === Caras enfermas ===
	"😷": "cara con mascarilla",
	"🤒": "cara enferma con termómetro",
	"🤕": "cara con vendaje",
	"🤢": "cara mareada",
	"🤮": "cara vomitando",
	"🤧": "cara estornudando",
	"🥵": "cara acalorada",
	"🥶": "cara congelada",
	"🥴": "cara aturdida",
	"😵": "cara atontada",
	"😵‍💫": "cara con ojos en espiral",
	"🤯": "cabeza explotando",

	# === Caras con gorro/gafas ===
	"🤠": "cara con sombrero de vaquero",
	"🥸": "cara disfrazada",
	"😎": "cara con gafas de sol",
	"🤓": "cara de empollón",
	"🧐": "cara con monóculo",

	# === Caras preocupadas ===
	"😕": "cara confundida",
	"🫤": "cara con boca torcida",
	"😟": "cara preocupada",
	"🙁": "cara ligeramente triste",
	"☹️": "cara triste",
	"😮": "cara sorprendida",
	"😯": "cara asombrada",
	"😲": "cara impactada",
	"😳": "cara sonrojada",
	"🥺": "cara suplicando",
	"🥹": "cara aguantando las lágrimas",
	"😦": "cara de preocupación",
	"😧": "cara angustiada",
	"😨": "cara asustada",
	"😰": "cara con ansiedad",
	"😥": "cara triste con alivio",
	"😢": "cara llorando",
	"😭": "cara llorando mucho",
	"😱": "cara gritando de miedo",
	"😖": "cara frustrada",
	"😣": "cara sufriendo",
	"😞": "cara decepcionada",
	"😓": "cara abatida con sudor",
	"😩": "cara agotada",
	"😫": "cara exhausta",
	"🥱": "bostezo",

	# === Caras enfadadas ===
	"😤": "cara resoplando",
	"😡": "cara enfadada",
	"😠": "cara molesta",
	"🤬": "cara insultando",
	"😈": "cara diabólica sonriente",
	"👿": "cara diabólica enfadada",
	"💀": "calavera",
	"☠️": "calavera con huesos",

	# === Caras de fantasía ===
	"💩": "caca sonriente",
	"🤡": "payaso",
	"👹": "ogro",
	"👺": "duende",
	"👻": "fantasma",
	"👽": "alienígena",
	"👾": "monstruo alienígena",
	"🤖": "robot",
	"😺": "gato sonriendo",
	"😸": "gato sonriendo con ojos sonrientes",
	"😹": "gato llorando de risa",
	"😻": "gato enamorado",
	"😼": "gato pícaro",
	"😽": "gato besando",
	"🙀": "gato asustado",
	"😿": "gato llorando",
	"😾": "gato enfadado",
	"🙈": "mono tapándose los ojos",
	"🙉": "mono tapándose los oídos",
	"🙊": "mono tapándose la boca",

	# === Corazones ===
	"❤️": "corazón rojo",
	"🧡": "corazón naranja",
	"💛": "corazón amarillo",
	"💚": "corazón verde",
	"💙": "corazón azul",
	"💜": "corazón morado",
	"🖤": "corazón negro",
	"🤍": "corazón blanco",
	"🤎": "corazón marrón",
	"❤️‍🔥": "corazón en llamas",
	"❤️‍🩹": "corazón con vendaje",
	"💔": "corazón roto",
	"❣️": "exclamación de corazón",
	"💕": "dos corazones",
	"💞": "corazones girando",
	"💓": "corazón latiendo",
	"💗": "corazón creciendo",
	"💖": "corazón brillante",
	"💘": "corazón con flecha",
	"💝": "corazón con lazo",
	"🩷": "corazón rosa",
	"🩵": "corazón celeste",
	"🩶": "corazón gris",

	# === Manos y gestos ===
	"👍": "pulgar hacia arriba",
	"👎": "pulgar hacia abajo",
	"👌": "gesto de acuerdo",
	"🤌": "gesto italiano",
	"🤏": "pellizco",
	"✌️": "victoria",
	"🤞": "dedos cruzados",
	"🫰": "mano con índice y pulgar cruzados",
	"🤟": "te quiero en lengua de signos",
	"🤘": "cuernos de rock",
	"🤙": "llámame",
	"👈": "dedo apuntando a la izquierda",
	"👉": "dedo apuntando a la derecha",
	"👆": "dedo apuntando arriba",
	"👇": "dedo apuntando abajo",
	"☝️": "dedo índice apuntando arriba",
	"🫵": "dedo apuntando al espectador",
	"👏": "aplausos",
	"🙌": "manos levantadas",
	"🫶": "manos formando corazón",
	"👐": "manos abiertas",
	"🤲": "palmas juntas hacia arriba",
	"🤝": "apretón de manos",
	"🙏": "manos juntas",
	"✍️": "mano escribiendo",
	"💅": "pintándose las uñas",
	"🤳": "selfie",
	"💪": "bíceps",
	"🦾": "brazo mecánico",
	"🖕": "dedo medio",
	"✊": "puño levantado",
	"👊": "puñetazo",
	"🤛": "puño izquierdo",
	"🤜": "puño derecho",
	"👋": "mano saludando",
	"🤚": "mano levantada",
	"🖐️": "mano abierta con dedos separados",
	"✋": "mano levantada",
	"🖖": "saludo vulcano",
	"🫱": "mano derecha",
	"🫲": "mano izquierda",
	"🫳": "palma hacia abajo",
	"🫴": "palma hacia arriba",

	# === Personas ===
	"👶": "bebé",
	"🧒": "niño",
	"👦": "chico",
	"👧": "chica",
	"🧑": "persona adulta",
	"👨": "hombre",
	"👩": "mujer",
	"🧓": "persona mayor",
	"👴": "hombre mayor",
	"👵": "mujer mayor",
	"🤷": "encogimiento de hombros",
	"🤦": "mano en la cara",
	"🙅": "gesto de no",
	"🙆": "gesto de sí",
	"🙇": "reverencia",
	"🙍": "persona frunciendo el ceño",
	"🙎": "persona haciendo pucheros",
	"💁": "persona con la mano extendida",
	"🙋": "persona levantando la mano",
	"🧏": "persona sorda",
	"💆": "persona recibiendo masaje",
	"💇": "persona cortándose el pelo",
	"🚶": "persona caminando",
	"🧍": "persona de pie",
	"🧎": "persona arrodillada",
	"🏃": "persona corriendo",
	"💃": "mujer bailando",
	"🕺": "hombre bailando",
	"👫": "pareja hombre y mujer",
	"👬": "dos hombres",
	"👭": "dos mujeres",
	"👪": "familia",

	# === Animales ===
	"🐶": "cara de perro",
	"🐕": "perro",
	"🐩": "caniche",
	"🐺": "lobo",
	"🦊": "zorro",
	"🦝": "mapache",
	"🐱": "cara de gato",
	"🐈": "gato",
	"🦁": "león",
	"🐯": "tigre",
	"🐆": "leopardo",
	"🐴": "cara de caballo",
	"🐎": "caballo",
	"🦄": "unicornio",
	"🐮": "cara de vaca",
	"🐂": "buey",
	"🐃": "búfalo",
	"🐄": "vaca",
	"🐷": "cara de cerdo",
	"🐖": "cerdo",
	"🐗": "jabalí",
	"🐏": "carnero",
	"🐑": "oveja",
	"🐐": "cabra",
	"🐪": "camello",
	"🐫": "camello de dos jorobas",
	"🦒": "jirafa",
	"🐘": "elefante",
	"🦏": "rinoceronte",
	"🐭": "cara de ratón",
	"🐹": "hámster",
	"🐰": "cara de conejo",
	"🐻": "cara de oso",
	"🐻‍❄️": "oso polar",
	"🐨": "koala",
	"🐼": "panda",
	"🐸": "cara de rana",
	"🐵": "cara de mono",
	"🐔": "gallina",
	"🐧": "pingüino",
	"🦅": "águila",
	"🦆": "pato",
	"🦉": "búho",
	"🐍": "serpiente",
	"🐢": "tortuga",
	"🦎": "lagarto",
	"🐙": "pulpo",
	"🦈": "tiburón",
	"🐳": "ballena",
	"🐬": "delfín",
	"🐟": "pez",
	"🐠": "pez tropical",
	"🐡": "pez globo",
	"🦋": "mariposa",
	"🐛": "oruga",
	"🐝": "abeja",
	"🐞": "mariquita",
	"🦗": "grillo",
	"🕷️": "araña",
	"🦂": "escorpión",
	"🐾": "huellas de animal",

	# === Comida y bebida ===
	"🍎": "manzana roja",
	"🍏": "manzana verde",
	"🍐": "pera",
	"🍊": "naranja",
	"🍋": "limón",
	"🍌": "plátano",
	"🍉": "sandía",
	"🍇": "uvas",
	"🍓": "fresa",
	"🫐": "arándanos",
	"🍈": "melón",
	"🍒": "cerezas",
	"🍑": "melocotón",
	"🥭": "mango",
	"🍍": "piña",
	"🥥": "coco",
	"🥝": "kiwi",
	"🍅": "tomate",
	"🥑": "aguacate",
	"🥦": "brócoli",
	"🥒": "pepino",
	"🌶️": "guindilla",
	"🫑": "pimiento",
	"🌽": "maíz",
	"🥕": "zanahoria",
	"🧄": "ajo",
	"🧅": "cebolla",
	"🥔": "patata",
	"🍠": "boniato",
	"🍞": "pan",
	"🥖": "baguete",
	"🥐": "cruasán",
	"🧀": "queso",
	"🍳": "huevo frito",
	"🥚": "huevo",
	"🥓": "beicon",
	"🥩": "carne",
	"🍗": "muslo de pollo",
	"🍖": "carne con hueso",
	"🌭": "perrito caliente",
	"🍔": "hamburguesa",
	"🍟": "patatas fritas",
	"🍕": "pizza",
	"🥪": "sándwich",
	"🌮": "taco",
	"🌯": "burrito",
	"🥗": "ensalada",
	"🍝": "espaguetis",
	"🍜": "sopa de fideos",
	"🍲": "guiso",
	"🍛": "arroz con curry",
	"🍣": "sushi",
	"🍱": "caja bento",
	"🥟": "empanadilla",
	"🍩": "dónut",
	"🍪": "galleta",
	"🎂": "tarta de cumpleaños",
	"🍰": "porción de tarta",
	"🧁": "magdalena",
	"🥧": "pastel",
	"🍫": "chocolate",
	"🍬": "caramelo",
	"🍭": "piruleta",
	"🍮": "flan",
	"🍯": "tarro de miel",
	"🍼": "biberón",
	"☕": "taza de café",
	"🫖": "tetera",
	"🍵": "taza de té",
	"🍺": "jarra de cerveza",
	"🍻": "brindis con cerveza",
	"🥂": "brindis con champán",
	"🍷": "copa de vino",
	"🍸": "cóctel",
	"🍹": "bebida tropical",
	"🧃": "zumo en caja",
	"🧊": "hielo",
	"🥤": "vaso con pajita",

	# === Viajes y lugares ===
	"🏠": "casa",
	"🏡": "casa con jardín",
	"🏢": "edificio de oficinas",
	"🏣": "oficina de correos",
	"🏥": "hospital",
	"🏦": "banco",
	"🏨": "hotel",
	"🏩": "hotel del amor",
	"🏪": "tienda",
	"🏫": "escuela",
	"🏬": "centro comercial",
	"🏭": "fábrica",
	"🏰": "castillo",
	"🗼": "torre",
	"🗽": "estatua de la libertad",
	"⛪": "iglesia",
	"🕌": "mezquita",
	"🚗": "coche",
	"🚕": "taxi",
	"🚌": "autobús",
	"🚎": "trolebús",
	"🏎️": "coche de carreras",
	"🚓": "coche de policía",
	"🚑": "ambulancia",
	"🚒": "camión de bomberos",
	"🚐": "furgoneta",
	"🛻": "camioneta",
	"🚚": "camión",
	"🚲": "bicicleta",
	"🛵": "moto scooter",
	"🏍️": "motocicleta",
	"✈️": "avión",
	"🛩️": "avioneta",
	"🚀": "cohete",
	"🛸": "platillo volante",
	"🚁": "helicóptero",
	"🚂": "locomotora",
	"🚆": "tren",
	"🚇": "metro",
	"🚢": "barco",
	"⛵": "velero",
	"🚤": "lancha rápida",
	"⛽": "gasolinera",

	# === Objetos ===
	"📱": "teléfono móvil",
	"📲": "móvil con flecha",
	"💻": "portátil",
	"🖥️": "ordenador de escritorio",
	"🖨️": "impresora",
	"⌨️": "teclado",
	"🖱️": "ratón de ordenador",
	"🖲️": "bola de seguimiento",
	"💾": "disquete",
	"💿": "disco compacto",
	"📀": "DVD",
	"📧": "correo electrónico",
	"📨": "sobre entrante",
	"📩": "sobre con flecha",
	"📮": "buzón de correos",
	"📝": "nota con lápiz",
	"📚": "libros",
	"📕": "libro rojo cerrado",
	"📖": "libro abierto",
	"📗": "libro verde",
	"📘": "libro azul",
	"📙": "libro naranja",
	"📓": "cuaderno",
	"📒": "libro de contabilidad",
	"📔": "cuaderno decorativo",
	"📰": "periódico",
	"🗞️": "periódico enrollado",
	"🔑": "llave",
	"🗝️": "llave antigua",
	"🔒": "candado cerrado",
	"🔓": "candado abierto",
	"🔏": "candado con pluma",
	"🔐": "candado con llave",
	"📌": "chincheta",
	"📎": "clip",
	"🖇️": "clips unidos",
	"✏️": "lápiz",
	"✒️": "pluma negra",
	"🖊️": "bolígrafo",
	"🖋️": "pluma estilográfica",
	"📐": "escuadra",
	"📏": "regla",
	"🔍": "lupa hacia la izquierda",
	"🔎": "lupa hacia la derecha",
	"💡": "bombilla",
	"🔦": "linterna",
	"🕯️": "vela",
	"🪫": "batería baja",
	"🔋": "batería",
	"🔌": "enchufe",
	"🧲": "imán",
	"🧪": "tubo de ensayo",
	"🧫": "placa de Petri",
	"🧬": "ADN",
	"🔬": "microscopio",
	"🔭": "telescopio",
	"📡": "antena parabólica",
	"💊": "pastilla",
	"💉": "jeringuilla",
	"🩹": "tirita",
	"🩺": "estetoscopio",
	"🪞": "espejo",
	"🪟": "ventana",
	"🛏️": "cama",
	"🛋️": "sofá",
	"🪑": "silla",
	"🚪": "puerta",
	"🧳": "maleta",

	# === Símbolos y señales ===
	"🔥": "fuego",
	"⭐": "estrella",
	"🌟": "estrella brillante",
	"✨": "destellos",
	"⚡": "rayo",
	"💯": "cien puntos",
	"✔️": "marca de verificación",
	"✅": "marca verde",
	"❌": "marca de cierre",
	"❎": "marca de cierre en cuadro",
	"⚠️": "advertencia",
	"🚫": "prohibido",
	"⛔": "entrada prohibida",
	"🔴": "círculo rojo",
	"🟠": "círculo naranja",
	"🟡": "círculo amarillo",
	"🟢": "círculo verde",
	"🔵": "círculo azul",
	"🟣": "círculo morado",
	"🟤": "círculo marrón",
	"⚫": "círculo negro",
	"⚪": "círculo blanco",
	"🔶": "rombo naranja grande",
	"🔷": "rombo azul grande",
	"🔸": "rombo naranja pequeño",
	"🔹": "rombo azul pequeño",
	"▪️": "cuadrado negro pequeño",
	"▫️": "cuadrado blanco pequeño",
	"◾": "cuadrado medio negro",
	"◽": "cuadrado medio blanco",
	"⬛": "cuadrado negro grande",
	"⬜": "cuadrado blanco grande",
	"🔺": "triángulo rojo hacia arriba",
	"🔻": "triángulo rojo hacia abajo",
	"💠": "rombo con punto",
	"🔘": "botón de opción",
	"🔲": "botón cuadrado negro",
	"🔳": "botón cuadrado blanco",
	"♻️": "símbolo de reciclaje",
	"♾️": "infinito",

	# === Eventos y celebración ===
	"🎉": "fiesta",
	"🎊": "confeti",
	"🎈": "globo",
	"🎁": "regalo",
	"🎀": "lazo",
	"🎄": "árbol de navidad",
	"🎃": "calabaza",
	"🎆": "fuegos artificiales",
	"🎇": "bengala",
	"🧨": "petardo",
	"🎗️": "lazo conmemorativo",
	"🎟️": "entrada",
	"🎫": "ticket",
	"🏆": "trofeo",
	"🥇": "medalla de oro",
	"🥈": "medalla de plata",
	"🥉": "medalla de bronce",
	"⚽": "balón de fútbol",
	"🏀": "balón de baloncesto",
	"🏈": "balón de fútbol americano",
	"⚾": "béisbol",
	"🎾": "tenis",
	"🏐": "voleibol",
	"🎱": "billar",
	"🏓": "ping pong",
	"🎳": "bolos",
	"🎮": "mando de videojuego",
	"🕹️": "joystick",
	"🎲": "dado",
	"🧩": "pieza de puzle",
	"♟️": "peón de ajedrez",
	"🎵": "nota musical",
	"🎶": "notas musicales",
	"🎤": "micrófono",
	"🎧": "auriculares",
	"🎸": "guitarra",
	"🎹": "teclado musical",
	"🥁": "tambor",
	"🎷": "saxofón",
	"🎺": "trompeta",
	"🎻": "violín",
	"📷": "cámara de fotos",
	"📸": "cámara con flash",
	"📹": "videocámara",
	"🎬": "claqueta",
	"📺": "televisor",
	"📻": "radio",
	"🎨": "paleta de pintor",

	# === Sonidos y comunicación ===
	"🔊": "altavoz alto",
	"🔉": "altavoz medio",
	"🔈": "altavoz bajo",
	"🔇": "sonido silenciado",
	"📢": "megáfono",
	"📣": "megáfono animando",
	"🔔": "campana",
	"🔕": "campana silenciada",
	"💬": "bocadillo de diálogo",
	"💭": "bocadillo de pensamiento",
	"🗯️": "bocadillo de enfado",
	"🗨️": "bocadillo de habla izquierdo",

	# === Naturaleza y clima ===
	"🌈": "arcoíris",
	"☀️": "sol",
	"🌤️": "sol con nubes",
	"⛅": "sol parcialmente nublado",
	"🌥️": "sol detrás de nubes",
	"☁️": "nube",
	"🌦️": "sol con lluvia",
	"🌧️": "lluvia",
	"⛈️": "tormenta",
	"🌩️": "nube con rayo",
	"🌪️": "tornado",
	"🌫️": "niebla",
	"❄️": "copo de nieve",
	"☃️": "muñeco de nieve",
	"⛄": "muñeco de nieve sin nieve",
	"🌊": "ola",
	"💧": "gota de agua",
	"☔": "paraguas con lluvia",
	"🌙": "luna creciente",
	"🌕": "luna llena",
	"🌑": "luna nueva",
	"⭐": "estrella",
	"🌠": "estrella fugaz",
	"🌌": "vía láctea",
	"🌹": "rosa",
	"🌷": "tulipán",
	"🌻": "girasol",
	"🌺": "hibisco",
	"🌸": "flor de cerezo",
	"💐": "ramo de flores",
	"🌲": "árbol perenne",
	"🌳": "árbol de hoja caduca",
	"🌴": "palmera",
	"🌵": "cactus",
	"🍀": "trébol de cuatro hojas",
	"🍁": "hoja de arce",
	"🍂": "hojas caídas",
	"🍃": "hoja al viento",
	"🌿": "hierba",
	"🪴": "planta en maceta",

	# === Tiempo y relojes ===
	"⏰": "reloj despertador",
	"⌚": "reloj de pulsera",
	"⏱️": "cronómetro",
	"⏲️": "temporizador",
	"🕐": "una en punto",
	"📅": "calendario",
	"🗓️": "calendario de espiral",
	"⌛": "reloj de arena acabado",
	"⏳": "reloj de arena en marcha",

	# === Banderas populares ===
	"🏳️": "bandera blanca",
	"🏴": "bandera negra",
	"🏁": "bandera a cuadros",
	"🚩": "bandera triangular",
	"🏳️‍🌈": "bandera arcoíris",
	"🇪🇸": "bandera de España",
	"🇲🇽": "bandera de México",
	"🇦🇷": "bandera de Argentina",
	"🇨🇴": "bandera de Colombia",
	"🇺🇸": "bandera de Estados Unidos",
	"🇬🇧": "bandera de Reino Unido",
	"🇫🇷": "bandera de Francia",
	"🇩🇪": "bandera de Alemania",
	"🇮🇹": "bandera de Italia",
	"🇧🇷": "bandera de Brasil",
	"🇯🇵": "bandera de Japón",
	"🇨🇳": "bandera de China",
	"🇷🇺": "bandera de Rusia",
	"🇵🇹": "bandera de Portugal",

	# === Otros ===
	"💤": "dormido",
	"💢": "símbolo de enfado",
	"💥": "explosión",
	"💦": "gotas de sudor",
	"💨": "ráfaga de viento",
	"🕳️": "agujero",
	"💣": "bomba",
	"🧿": "ojo turco",
	"♿": "símbolo de accesibilidad",
	"🚻": "lavabo",
	"🚮": "tirar basura aquí",
	"🚰": "agua potable",
	"♂️": "símbolo masculino",
	"♀️": "símbolo femenino",
	"⚧️": "símbolo transgénero",
	"✝️": "cruz latina",
	"☪️": "media luna y estrella",
	"🕉️": "om",
	"☮️": "símbolo de paz",
	"☯️": "yin yang",
	"🔯": "estrella de seis puntas",
	"ℹ️": "información",
	"🆗": "botón OK",
	"🆘": "botón SOS",
	"🆕": "botón nuevo",
	"🆓": "botón gratis",
	"🔝": "flecha arriba",
	"🔙": "flecha atrás",
	"🔛": "botón ON",
	"🔜": "flecha pronto",
	"🔚": "botón FIN",

	# === Zodíaco ===
	"♈": "Aries",
	"♉": "Tauro",
	"♊": "Géminis",
	"♋": "Cáncer",
	"♌": "Leo",
	"♍": "Virgo",
	"♎": "Libra",
	"♏": "Escorpio",
	"♐": "Sagitario",
	"♑": "Capricornio",
	"♒": "Acuario",
	"♓": "Piscis",
	"⛎": "Ofiuco",

	# === Relojes ===
	"🕑": "dos en punto",
	"🕒": "tres en punto",
	"🕓": "cuatro en punto",
	"🕔": "cinco en punto",
	"🕕": "seis en punto",
	"🕖": "siete en punto",
	"🕗": "ocho en punto",
	"🕘": "nueve en punto",
	"🕙": "diez en punto",
	"🕚": "once en punto",
	"🕛": "doce en punto",
	"🕜": "una y media",
	"🕝": "dos y media",
	"🕞": "tres y media",
	"🕟": "cuatro y media",
	"🕠": "cinco y media",
	"🕡": "seis y media",
	"🕢": "siete y media",
	"🕣": "ocho y media",
	"🕤": "nueve y media",
	"🕥": "diez y media",
	"🕦": "once y media",
	"🕧": "doce y media",

	# === Flechas ===
	"⬆️": "flecha hacia arriba",
	"⬇️": "flecha hacia abajo",
	"⬅️": "flecha hacia la izquierda",
	"➡️": "flecha hacia la derecha",
	"↗️": "flecha diagonal arriba derecha",
	"↘️": "flecha diagonal abajo derecha",
	"↙️": "flecha diagonal abajo izquierda",
	"↖️": "flecha diagonal arriba izquierda",
	"↕️": "flecha arriba y abajo",
	"↔️": "flecha izquierda y derecha",
	"↩️": "flecha curva izquierda",
	"↪️": "flecha curva derecha",
	"⤴️": "flecha curva hacia arriba",
	"⤵️": "flecha curva hacia abajo",
	"🔃": "flechas verticales en círculo",
	"🔄": "flechas circulares en sentido contrario",
	"🔀": "reproducción aleatoria",
	"🔁": "repetición",
	"🔂": "repetición de una pista",
	"▶️": "reproducir",
	"⏩": "avance rápido",
	"⏭️": "pista siguiente",
	"⏯️": "reproducir o pausar",
	"◀️": "rebobinar",
	"⏪": "rebobinado rápido",
	"⏮️": "pista anterior",
	"⏸️": "pausa",
	"⏹️": "detener",
	"⏺️": "grabar",
	"⏏️": "expulsar",

	# === Ropa y accesorios ===
	"👓": "gafas",
	"🕶️": "gafas de sol",
	"🥽": "gafas de protección",
	"👔": "corbata",
	"👕": "camiseta",
	"👖": "pantalón vaquero",
	"🧣": "bufanda",
	"🧤": "guantes",
	"🧥": "abrigo",
	"🧦": "calcetines",
	"👗": "vestido",
	"👘": "kimono",
	"🥻": "sari",
	"🩱": "bañador de una pieza",
	"🩲": "calzoncillo",
	"🩳": "pantalón corto",
	"👙": "bikini",
	"👚": "blusa",
	"👛": "monedero",
	"👜": "bolso",
	"👝": "bolsa de mano",
	"🎒": "mochila",
	"👞": "zapato de hombre",
	"👟": "zapatilla deportiva",
	"🥾": "bota de senderismo",
	"🥿": "zapato plano",
	"👠": "zapato de tacón",
	"👡": "sandalia",
	"🩰": "zapatilla de ballet",
	"👢": "bota de mujer",
	"👑": "corona",
	"👒": "sombrero con lazo",
	"🎩": "sombrero de copa",
	"🎓": "birrete de graduación",
	"🧢": "gorra",
	"⛑️": "casco de rescate",
	"💎": "diamante",
	"💍": "anillo",
	"👰": "persona con velo",
	"🤵": "persona con esmoquin",

	# === Herramientas ===
	"🔧": "llave inglesa",
	"🔨": "martillo",
	"⚒️": "martillo y pico",
	"🛠️": "martillo y llave",
	"🔩": "tuerca y tornillo",
	"⚙️": "engranaje",
	"🗜️": "mordaza",
	"⛏️": "pico",
	"🪓": "hacha",
	"🪚": "sierra",
	"🪛": "destornillador",
	"🪝": "gancho",
	"🪜": "escalera",
	"🧰": "caja de herramientas",
	"✂️": "tijeras",
	"🗡️": "daga",
	"⚔️": "espadas cruzadas",
	"🔫": "pistola de agua",
	"🏹": "arco y flecha",
	"🛡️": "escudo",
	"🪤": "trampa para ratones",

	# === Hogar ===
	"🚿": "ducha",
	"🛁": "bañera",
	"🧹": "escoba",
	"🧺": "cesto de ropa",
	"🧻": "papel higiénico",
	"🪣": "cubo",
	"🧴": "bote de loción",
	"🪥": "cepillo de dientes",
	"🧽": "esponja",
	"🪠": "desatascador",
	"🧯": "extintor",
	"🛒": "carrito de compras",
	"🪙": "moneda",
	"💰": "bolsa de dinero",
	"💳": "tarjeta de crédito",
	"💵": "billete de dólar",
	"💴": "billete de yen",
	"💶": "billete de euro",
	"💷": "billete de libra",
	"🧾": "recibo",

	# === Cuerpo ===
	"👀": "ojos",
	"👁️": "ojo",
	"👅": "lengua",
	"👄": "boca",
	"🦷": "diente",
	"🦴": "hueso",
	"🧠": "cerebro",
	"🫀": "corazón anatómico",
	"🫁": "pulmones",
	"🦿": "pierna mecánica",
	"🦶": "pie",
	"🦵": "pierna",
	"👂": "oreja",
	"🦻": "oreja con audífono",
	"👃": "nariz",
	"🫦": "labios mordiéndose",
	"🦲": "persona calva",
	"🦳": "pelo blanco",
	"🦰": "pelo rojo",
	"🦱": "pelo rizado",

	# === Más animales ===
	"🦓": "cebra",
	"🦍": "gorila",
	"🦧": "orangután",
	"🐿️": "ardilla",
	"🦫": "castor",
	"🦔": "erizo",
	"🦇": "murciélago",
	"🦥": "perezoso",
	"🦦": "nutria",
	"🦨": "mofeta",
	"🦘": "canguro",
	"🦡": "tejón",
	"🦃": "pavo",
	"🐓": "gallo",
	"🐣": "pollito saliendo del huevo",
	"🐤": "pollito",
	"🐥": "pollito de frente",
	"🐦": "pájaro",
	"🦜": "loro",
	"🦢": "cisne",
	"🦩": "flamenco",
	"🕊️": "paloma",
	"🦚": "pavo real",
	"🐊": "cocodrilo",
	"🦕": "dinosaurio",
	"🦖": "tiranosaurio",
	"🐲": "cara de dragón",
	"🐉": "dragón",
	"🦐": "gamba",
	"🦞": "langosta",
	"🦀": "cangrejo",
	"🦑": "calamar",
	"🐚": "concha",
	"🐌": "caracol",
	"🐜": "hormiga",
	"🦟": "mosquito",
	"🪰": "mosca",
	"🪱": "gusano",
	"🪲": "escarabajo",
	"🪳": "cucaracha",
	"🦠": "microbio",

	# === Más banderas ===
	"🇨🇱": "bandera de Chile",
	"🇵🇪": "bandera de Perú",
	"🇻🇪": "bandera de Venezuela",
	"🇪🇨": "bandera de Ecuador",
	"🇧🇴": "bandera de Bolivia",
	"🇵🇾": "bandera de Paraguay",
	"🇺🇾": "bandera de Uruguay",
	"🇨🇷": "bandera de Costa Rica",
	"🇵🇦": "bandera de Panamá",
	"🇨🇺": "bandera de Cuba",
	"🇩🇴": "bandera de República Dominicana",
	"🇬🇹": "bandera de Guatemala",
	"🇭🇳": "bandera de Honduras",
	"🇸🇻": "bandera de El Salvador",
	"🇳🇮": "bandera de Nicaragua",
	"🇰🇷": "bandera de Corea del Sur",
	"🇮🇳": "bandera de India",
	"🇦🇺": "bandera de Australia",
	"🇨🇦": "bandera de Canadá",
	"🇳🇱": "bandera de Países Bajos",
	"🇧🇪": "bandera de Bélgica",
	"🇨🇭": "bandera de Suiza",
	"🇦🇹": "bandera de Austria",
	"🇸🇪": "bandera de Suecia",
	"🇳🇴": "bandera de Noruega",
	"🇩🇰": "bandera de Dinamarca",
	"🇫🇮": "bandera de Finlandia",
	"🇵🇱": "bandera de Polonia",
	"🇬🇷": "bandera de Grecia",
	"🇹🇷": "bandera de Turquía",
	"🇮🇱": "bandera de Israel",
	"🇪🇬": "bandera de Egipto",
	"🇿🇦": "bandera de Sudáfrica",
	"🇳🇬": "bandera de Nigeria",
	"🇲🇦": "bandera de Marruecos",
	"🇹🇭": "bandera de Tailandia",
	"🇻🇳": "bandera de Vietnam",
	"🇵🇭": "bandera de Filipinas",
	"🇮🇩": "bandera de Indonesia",
	"🇲🇾": "bandera de Malasia",
	"🇸🇬": "bandera de Singapur",
	"🇳🇿": "bandera de Nueva Zelanda",
	"🇮🇪": "bandera de Irlanda",
	"🇺🇦": "bandera de Ucrania",
	"🇷🇴": "bandera de Rumania",
	"🇭🇺": "bandera de Hungría",
	"🇨🇿": "bandera de República Checa",

	# === Más comida ===
	"🫒": "aceituna",
	"🫘": "judía",
	"🥜": "cacahuete",
	"🌰": "castaña",
	"🫚": "jengibre",
	"🥯": "rosquilla",
	"🥞": "tortitas",
	"🧇": "gofre",
	"🫔": "tamal",
	"🥘": "paella",
	"🫕": "fondue",
	"🥙": "kebab",
	"🧆": "falafel",
	"🥮": "pastel de luna",
	"🍡": "dango",
	"🍧": "granizado",
	"🍨": "helado",
	"🍦": "cucurucho de helado",
	"🥜": "cacahuete",
	"🫗": "vertiendo líquido",
	"🧋": "té de burbujas",
	"🍶": "sake",
	"🥃": "vaso de whisky",
	"🧉": "mate",

	# === Actividades y deporte ===
	"🧗": "persona escalando",
	"🏊": "persona nadando",
	"🏄": "persona surfeando",
	"🚣": "persona remando",
	"🧘": "persona meditando",
	"🛀": "persona bañándose",
	"🏋️": "persona levantando pesas",
	"🤸": "persona haciendo voltereta",
	"🤼": "personas luchando",
	"🤽": "persona jugando al waterpolo",
	"🤾": "persona jugando al balonmano",
	"🤺": "persona practicando esgrima",
	"🏌️": "persona jugando al golf",
	"🏇": "jockey",
	"🧑‍🎤": "cantante",
	"🧑‍🍳": "cocinero",
	"🧑‍🏫": "profesor",
	"🧑‍🎓": "estudiante",
	"🧑‍⚕️": "profesional de la salud",
	"🧑‍🌾": "agricultor",
	"🧑‍🔧": "mecánico",
	"🧑‍🏭": "trabajador de fábrica",
	"🧑‍💼": "oficinista",
	"🧑‍🔬": "científico",
	"🧑‍💻": "informático",
	"🧑‍🎨": "artista",
	"🧑‍🚒": "bombero",
	"🧑‍✈️": "piloto",
	"🧑‍🚀": "astronauta",
	"🧑‍⚖️": "juez",
	"🏊‍♂️": "hombre nadando",
	"🏊‍♀️": "mujer nadando",
	"🚴": "persona en bicicleta",
	"🚴‍♂️": "hombre en bicicleta",
	"🚴‍♀️": "mujer en bicicleta",
	"🤹": "persona haciendo malabarismos",
	"🎯": "diana",
	"🪀": "yoyó",
	"🪁": "cometa",
	"🏏": "críquet",
	"🏑": "hockey hierba",
	"🏒": "hockey hielo",
	"🥍": "lacrosse",
	"🥊": "guante de boxeo",
	"🥋": "kimono de artes marciales",
	"⛷️": "esquiador",
	"🏂": "snowboard",
	"🛷": "trineo",
	"⛸️": "patín de hielo",
	"🥌": "piedra de curling",
	"🎣": "caña de pescar",
	"🎽": "camiseta de correr",
	"🎿": "esquís",
	"🛹": "monopatín",
	"🛼": "patín de ruedas",
	"🏋️‍♀️": "mujer levantando pesas",
	"🏋️‍♂️": "hombre levantando pesas",

	# === Seres fantásticos ===
	"🧙": "mago",
	"🧙‍♂️": "hombre mago",
	"🧙‍♀️": "mujer maga",
	"🧚": "hada",
	"🧛": "vampiro",
	"🧜": "persona sirena",
	"🧜‍♀️": "sirena",
	"🧜‍♂️": "tritón",
	"🧝": "elfo",
	"🧞": "genio",
	"🧟": "zombi",
	"🦸": "superhéroe",
	"🦹": "supervillano",
	"🥷": "ninja",
	"🧑‍🎄": "Papá Noel",
	"🤶": "Mamá Noel",
	"🧌": "trol",

	# === Más lugares y edificios ===
	"🏗️": "edificio en construcción",
	"🏘️": "casas",
	"🏚️": "casa abandonada",
	"🏛️": "edificio clásico",
	"🏤": "oficina de correos europea",
	"🏯": "castillo japonés",
	"🕍": "sinagoga",
	"🛕": "templo hindú",
	"⛩️": "santuario sintoísta",
	"🕋": "Kaaba",
	"⛲": "fuente",
	"⛺": "tienda de campaña",
	"🏕️": "camping",
	"🏖️": "playa con sombrilla",
	"🏜️": "desierto",
	"🏝️": "isla desierta",
	"🏞️": "parque nacional",
	"🗻": "monte Fuji",
	"🏔️": "montaña con nieve",
	"🌋": "volcán",

	# === Más vehículos y transporte ===
	"🚜": "tractor",
	"🚛": "camión articulado",
	"🚙": "todoterreno",
	"🛺": "mototaxi",
	"🚃": "vagón de tren",
	"🚋": "tranvía",
	"🚞": "tren de montaña",
	"🚝": "monorraíl",
	"🚠": "teleférico de montaña",
	"🚡": "teleférico",
	"🚟": "tren colgante",
	"🛶": "canoa",
	"🚏": "parada de autobús",
	"🛤️": "vías del tren",
	"🛣️": "autopista",
	"🚥": "semáforo horizontal",
	"🚦": "semáforo vertical",
	"🛑": "señal de stop",
	"⚓": "ancla",
	"🛟": "flotador",

	# === Más naturaleza ===
	"🌍": "globo terráqueo mostrando Europa y África",
	"🌎": "globo terráqueo mostrando América",
	"🌏": "globo terráqueo mostrando Asia",
	"🪐": "planeta con anillo",
	"☄️": "cometa",
	"💫": "estrella con estela",
	"🌔": "luna gibosa creciente",
	"🌖": "luna gibosa menguante",
	"🌗": "luna en cuarto menguante",
	"🌘": "luna menguante",
	"🌒": "luna creciente",
	"🌓": "luna en cuarto creciente",
	"🌝": "luna llena con cara",
	"🌛": "luna en cuarto creciente con cara",
	"🌜": "luna en cuarto menguante con cara",
	"🌞": "sol con cara",
	"🌼": "flor",
	"🪷": "flor de loto",
	"🪻": "jacinto",
	"🌾": "espiga de arroz",
	"☘️": "trébol",
	"🌱": "planta joven",
	"🪹": "nido vacío",
	"🪺": "nido con huevos",
	"🍄": "seta",
	"🪸": "coral",
	"🪨": "roca",
	"🪵": "tronco",
	"🏵️": "roseta",

	# === Símbolos japoneses y más ===
	"🈹": "descuento en japonés",
	"🈴": "aprobado en japonés",
	"🈺": "abierto en japonés",
	"🈯": "reservado en japonés",
	"🈷️": "mensual en japonés",
	"🈶": "no gratis en japonés",
	"🈵": "lleno en japonés",
	"🈸": "solicitud en japonés",
	"🈲": "prohibido en japonés",
	"🈳": "vacante en japonés",
	"🉐": "ganga en japonés",
	"🉑": "aceptable en japonés",
	"🔠": "letras mayúsculas",
	"🔡": "letras minúsculas",
	"🔢": "números",
	"🔣": "símbolos",
	"🔤": "letras del abecedario",
	"🅰️": "tipo de sangre A",
	"🅱️": "tipo de sangre B",
	"🆎": "tipo de sangre AB",
	"🅾️": "tipo de sangre O",
	"🆑": "botón borrar",
	"🆒": "botón genial",
	"🆔": "botón identidad",
	"🆙": "botón arriba",
	"🆚": "botón versus",
	"🈁": "aquí en japonés",
	"📛": "insignia con nombre",
	"⭕": "círculo rojo grande",
	"〽️": "marca alterna",
	"‼️": "doble exclamación",
	"⁉️": "exclamación e interrogación",
	"❓": "interrogación roja",
	"❔": "interrogación blanca",
	"❕": "exclamación blanca",
	"❗": "exclamación roja",
	"〰️": "guion ondulado",
	"©️": "copyright",
	"®️": "marca registrada",
	"™️": "marca comercial",
	"#️⃣": "tecla almohadilla",
	"*️⃣": "tecla asterisco",
	"0️⃣": "tecla cero",
	"1️⃣": "tecla uno",
	"2️⃣": "tecla dos",
	"3️⃣": "tecla tres",
	"4️⃣": "tecla cuatro",
	"5️⃣": "tecla cinco",
	"6️⃣": "tecla seis",
	"7️⃣": "tecla siete",
	"8️⃣": "tecla ocho",
	"9️⃣": "tecla nueve",
	"🔟": "tecla diez",
	"🏧": "cajero automático",
	"🚾": "aseo",
	"🅿️": "aparcamiento",
	"🛂": "control de pasaportes",
	"🛃": "aduana",
	"🛄": "recogida de equipaje",
	"🛅": "consigna",
}

# Emoticonos clásicos ASCII con descripciones en español
EMOTICONOS_MANUALES = {
	":)": "cara feliz",
	":-)": "cara feliz",
	"=)": "cara feliz",
	":]": "cara feliz",
	"(:": "cara feliz",
	"(-:": "cara feliz",
	":D": "risa",
	":-D": "risa",
	"=D": "risa",
	"XD": "risa fuerte",
	"X-D": "risa fuerte",
	"xD": "risa fuerte",
	"xd": "risa fuerte",
	":(": "cara triste",
	":-(": "cara triste",
	"=(": "cara triste",
	":[": "cara triste",
	"):": "cara triste",
	")-:": "cara triste",
	";)": "guiño",
	";-)": "guiño",
	";D": "guiño con risa",
	";-D": "guiño con risa",
	":P": "sacando la lengua",
	":-P": "sacando la lengua",
	":p": "sacando la lengua",
	":-p": "sacando la lengua",
	"=P": "sacando la lengua",
	"=p": "sacando la lengua",
	";P": "guiño con lengua",
	";-P": "guiño con lengua",
	";p": "guiño con lengua",
	";-p": "guiño con lengua",
	":O": "sorpresa",
	":-O": "sorpresa",
	":o": "sorpresa",
	":-o": "sorpresa",
	":|": "cara seria",
	":-|": "cara seria",
	":/": "duda o incomodidad",
	":-/": "duda o incomodidad",
	":\\": "duda o incomodidad",
	":-\\": "duda o incomodidad",
	":S": "confusión",
	":-S": "confusión",
	":s": "confusión",
	":-s": "confusión",
	":$": "vergüenza",
	":-$": "vergüenza",
	":*": "beso",
	":-*": "beso",
	"<3": "corazón",
	"</3": "corazón roto",
	":'(": "llanto",
	":'-(": "llanto",
	":')": "llorando de alegría",
	":'-)": "llorando de alegría",
	"^^": "alegría",
	"^_^": "alegría",
	"-_-": "aburrimiento",
	"o_O": "sorpresa o desconcierto",
	"O_o": "sorpresa o desconcierto",
	"._.": "expresión apagada",
	">:(": "enfado",
	">:-(": "enfado",
	":3": "cara tierna",
	":-3": "cara tierna",
}
